### ISSUE TITLE
Get "CUDA: an illegal memory access was encountered "

### ISSUE THREAD

**Issue by yancz1989** [apache/incubator-mxnet#10106]
Hi, all, I'm currently implementing a new operator. It runs smoothly using cpu, but under GPU, it get 
Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered

After change MXNET_ENGINE_TYPE, the traceback shows

Traceback (most recent call last):
  File "test.py", line 199, in <module>
    testTarget(conv1, int(sys.argv[1]))
  File "test.py", line 167, in testTarget
    output = mod.predict(val_iter)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/module/base_module.py", line 354, in predict
    outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/module/base_module.py", line 354, in <listcomp>
    outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1899, in copy
    return self.copyto(self.context)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1879, in copyto
    return _internal._copyto(self, out=hret)
  File "<string>", line 25, in _copyto
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:12:22] /mnt/disk1/xxx/rdr/dev/mxnet/mshadow/mshadow/./stream_gpu-inl.h:62: Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered

I log one "complete" after each cuda parallel kernel, and it seems it finish all the computing, but the get_outputs runs a failure.

Can someone give a hint on how such thing happens? Thanks for any advice.

**Comment by yancz1989** [comment]
the entire stack trace using naive engine is listed below:

Traceback (most recent call last):
  File "test.py", line 199, in <module>
    testTarget(conv1, int(sys.argv[1]))
  File "test.py", line 167, in testTarget
    output = mod.predict(val_iter)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/module/base_module.py", line 354, in predict
    outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/module/base_module.py", line 354, in <listcomp>
    outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1899, in copy
    return self.copyto(self.context)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1879, in copyto
    return _internal._copyto(self, out=hret)
  File "<string>", line 25, in _copyto
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:12:22] /mnt/disk1/yancz/rdr/dev/mxnet/mshadow/mshadow/./stream_gpu-inl.h:62: Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(dmlc::StackTrace()+0x4b) [0x7fffdc265d0b]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x2a) [0x7fffdc26622a]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mshadow::Stream<mshadow::gpu>::Wait()+0xd8) [0x7fffdea09eb8]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(+0x3334bb3) [0x7fffdea84bb3]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::engine::NaiveEngine::PushAsync(std::function<void (mxnet::RunContext, mxnet::engine::CallbackOnComplete)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, mxnet::FnProperty, int, char const*)+0x10c) [0x7fffdee9fd8c]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::CopyFromTo(mxnet::NDArray const&, mxnet::NDArray const&, int)+0x82b) [0x7fffdea8080b]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::imperative::PushFComputeEx(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const+0x71) [0x7fffdea0be51]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::imperative::PushFComputeEx(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)+0x482) [0x7fffdea1b6a2]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::Imperative::InvokeOp(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode, mxnet::OpStatePtr)+0x3a3) [0x7fffde9fc713]
[bt] (9) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::Imperative::Invoke(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&)+0x3aa) [0x7fffdea04e2a]


[20:12:22] src/resource.cc:246: Ignore CUDA Error [20:12:22] src/storage/./pooled_storage_manager.h:76: CUDA: an illegal memory access was encountered

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(dmlc::StackTrace()+0x4b) [0x7fffdc265d0b]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x2a) [0x7fffdc26622a]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(+0x3773cbc) [0x7fffdeec3cbc]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::storage::GPUPooledStorageManager::DirectFree(mxnet::Storage::Handle)+0x3f) [0x7fffdeece3bf]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::StorageImpl::DirectFree(mxnet::Storage::Handle)+0x69) [0x7fffdeec7c99]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(std::_Function_handler<void (mxnet::RunContext), mxnet::resource::ResourceManagerImpl::ResourceTempSpace::~ResourceTempSpace()::{lambda(mxnet::RunContext)#1}>::_M_invoke(std::_Any_data const&, mxnet::RunContext)+0xe3) [0x7fffdefc9db3]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(std::_Function_handler<void (mxnet::RunContext, mxnet::engine::CallbackOnComplete), mxnet::Engine::PushSync(std::function<void (mxnet::RunContext)>, mxnet::Context, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, mxnet::FnProperty, int, char const*)::{lambda(mxnet::RunContext, mxnet::engine::CallbackOnComplete)#1}>::_M_invoke(std::_Any_data const&, mxnet::RunContext, mxnet::engine::CallbackOnComplete)+0x23) [0x7fffde9b07a3]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::engine::NaiveEngine::DeleteVariable(std::function<void (mxnet::RunContext)>, mxnet::Context, mxnet::engine::Var*)+0x294) [0x7fffdeea0c24]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(mxnet::resource::ResourceManagerImpl::ResourceTempSpace::~ResourceTempSpace()+0x1af) [0x7fffdefcab1f]
[bt] (9) /usr/local/lib/python3.5/dist-packages/mxnet-1.1.0-py3.5.egg/mxnet/libmxnet.so(std::_Sp_counted_ptr<mxnet::resource::ResourceManagerImpl::ResourceTempSpace*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()+0x12) [0x7fffdefcabe2]

**Comment by sandeep-krishnamurthy** [comment]
Hello @yancz1989 - We recommend asking your usage related questions at https://discuss.mxnet.io/ 
Please reopen the issue, if you see any bug.

**Comment by Light--** [comment]
> Hello @yancz1989 - We recommend asking your usage related questions at https://discuss.mxnet.io/
@sandeep-krishnamurthy 
The question has been raised for years here: https://discuss.gluon.ai/t/topic/6913/3, but no progress...

**Comment by szha** [comment]
Hi @Light--, just because they have the same error message doesn't mean that they share the same cause. That's the reason why we request for bug reports with detailed environment information so that the developers can reproduce them. If you'd like to get a response on the problem, it would be great if you could do the same and share a bug report. Error messages alone like the above or your link won't provide enough information for us to attempt to solve the problem. Thanks for understanding.

**Comment by Light--** [comment]
> Thanks for understanding.

thanks and i understand. What's need here is someone really have experience/insights related to the above issue. I think the post like https://github.com/apache/incubator-mxnet/issues/10240 has described this very specifically. But providing mass info. in that way is inefficient unless someone knows what's the key info. is needed here. Btw, even doing feedback like that didn't get issue solved at last in that post. 

I am very willing to provide info. to get this solved, only wish you tell me what you need or what you need me for debugging this.

And please dont ask me to post on another forum or something like the answerer in https://github.com/apache/incubator-mxnet/issues/10240, there is no progress in solving the problem by changing the place it was posted.

No offense, thanks.

**Comment by szha** [comment]
Definitely. I agree that this thread isn't a usage question as illegal memory access should pretty much always be a framework problem (either bug or missed check). As a community we are slowly but steadily getting better at serving the community, and I look forward to working with you to solve the problem you face too!
