### ISSUE TITLE
Nvidia Jetson TX2  Check failed: (err) == (cudaSuccess) Name: mxnet_generic_kernel ErrStr:no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by yjcn** [apache/incubator-mxnet#11052]
## Description
Can't use GPU on TX2. I compile mxnet by myself(http://mxnet.incubator.apache.org/install/index.html 
 Linux-Python-GPU-Build from source),and there is no error while compiling.   When I test my mxnet, there is  an error.
![image](https://user-images.githubusercontent.com/8858803/40494255-fe5724f4-5fa6-11e8-88c8-4210864c7079.png)
 
Check failed: (err) == (cudaSuccess) Name: mxnet_generic_kernel ErrStr:no kernel image is available for execution on the device

![image](https://user-images.githubusercontent.com/8858803/40493729-e0f7c536-5fa5-11e8-97ec-fedc18d6733b.png)

## Environment info (Required)
TX2
CUDA 9.0 cuDNN 7.0
mxnet->master

**Comment by yjcn** [comment]
I have solved this problem. The default CUDA_ARCH doesn't contain the TX2 's CUDA_ARCH. So we need to add "CUDA_ARCH = -gencode arch=compute_62,code=sm_62" to make/config.mk manually.
(https://discuss.gluon.ai/t/topic/6589)
