### ISSUE TITLE
Bug in v1.2.0 ?

### ISSUE THREAD

**Issue by DuCheng2018** [apache/incubator-mxnet#12041]
## Description
Mxnet v1.2.0 gpu training failed on my computer.

## Environment info (Required)
Here is my environment: 
Windows 7
Gtx 1080 (x4)
Python 3.6.4 (anaconda3)
CUDA 8.0
mxnet-cu80

## Error Message:
I run the following code under mxnet v1.2.0.
>>import mxnet as mx
>>a = mx.nd.ones(1,mx.gpu()) 
#python.exe crash "cudaErrorCudartUnloading : device kernel image is invalid".
>>b = mx.nd.ones(1) #works well only using cpu

## What have I tried to solve it?
I have solved it just by using mxnet v1.1.0 instead.

**Comment by Roshrini** [comment]
@DuCheng2018 Do you get any particular error? Can you paste stacktrace?
@sandeep-krishnamurthy Could you add label: PendingRequestorInfo

**Comment by nswamy** [comment]
What platform are you running on(I am assuming Windows since I python.exe)?
What version of MXNet are installing ?  Do you have the corresponding version of CUDA installed in place? ie., `pip install mxnet-cu92` requires CUDA 9.2

**Comment by DuCheng2018** [comment]
The error message is "cudaErrorCudartUnloading : device kernel image is invalid"

**Comment by DuCheng2018** [comment]
When I train mnist dataset by :
python train_mnist --network lenet --gpus 0

#ERROR MESSAGE:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1513, in simple_bind
    ctypes.byref(exe_handle)))
  File "C:\Anaconda3\lib\site-packages\mxnet\base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:46:29] c:\jenkins\workspace\mxnet-tag\mxnet\src\storage\./pooled_storage_manager.h:108: cudaMa
lloc failed: device kernel image is invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_mnist.py", line 96, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "D:\MXNet\apache-mxnet-src-1.2.1-incubating\example\image-classification\common\fit.py", line 307, in fit
    monitor=monitor)
  File "C:\Anaconda3\lib\site-packages\mxnet\module\base_module.py", line 484, in fit
    for_training=True, force_rebind=force_rebind)
  File "C:\Anaconda3\lib\site-packages\mxnet\module\module.py", line 430, in bind
    state_names=self._state_names)
  File "C:\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 265, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "C:\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 361, in bind_exec
    shared_group))
  File "C:\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 639, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "C:\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1519, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 1, 28, 28)
softmax_label: (1,)
[16:46:29] c:\jenkins\workspace\mxnet-tag\mxnet\src\storage\./pooled_storage_manager.h:108: cudaMalloc failed: device ker
nel image is invalid

**Comment by DuCheng2018** [comment]
No one answer my question?

**Comment by hitdongfeng** [comment]
I have had the same problem as you and tried many times without success. I think it might be a bug

**Comment by lanking520** [comment]
@DuCheng2018 @hitdongfeng have you tried with 1.3 builds. Is this issue reproducible there?

**Comment by DuCheng2018** [comment]
Yeah, I have tried v1.3 which also didn’t work.




On 10/20/2018 06:49, Lanking wrote:

@DuCheng2018@hitdongfeng have you tried with 1.3 builds. Is this issue reproducible there?

**Comment by zachgk** [comment]
@mxnet-label-bot update [Bug, Build, Pending Requester Info]

Can you run our diagnostic script and comment with the output?

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

**Comment by DuCheng2018** [comment]
The bug is fixed after I update mxnet. Thx a lot.
