### ISSUE TITLE
GPU not found in toy example with new nvidia driver 396.54

### ISSUE THREAD

**Issue by JackTemaki** [apache/incubator-mxnet#12752]
Hello everyone,

MxNet crashes when I run  a toy example with GPU. I tried with Cuda 9.1 and Cuda 9.2, and with mxnet 1.3.0 and 1.2.1 installed via pip. It might have to do something with the driver version 396.54, because i am sure it worked at some point before.

## Error Message:
```
range(0, 1)
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    a = mx.nd.ones((2,3), mx.gpu())
  File "/usr/local/lib/python3.5/dist-packages/mxnet/ndarray/ndarray.py", line 2367, in ones
    return _internal._ones(shape=shape, ctx=ctx, dtype=dtype, **kwargs)
  File "<string>", line 34, in _ones
  File "/usr/local/lib/python3.5/dist-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/usr/local/lib/python3.5/dist-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:02:47] src/engine/threaded_engine.cc:320: Check failed: device_count_ > 0 (-1 vs. 0) GPU usage requires at least 1 GPU

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x382eea) [0x7f0108adbeea]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x383521) [0x7f0108adc521]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2ae9cbe) [0x7f010b242cbe]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2af07c8) [0x7f010b2497c8]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2b87a94) [0x7f010b2e0a94]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2b8c51c) [0x7f010b2e551c]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2b8d4d4) [0x7f010b2e64d4]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2aa4be9) [0x7f010b1fdbe9]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(MXImperativeInvokeEx+0x6f) [0x7f010b1fe1df]
[bt] (9) /usr/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f013be2ce20]
```

## Minimum reproducible example
```
import mxnet as mx
from mxnet import nd, autograd, gluon
import numpy as np

print(mx.test_utils.list_gpus())
a = mx.nd.ones((2,3), mx.gpu())
print((a*2).asnumpy())
```

I have no idea what else to try.

Best,
Jack

`nvcc --version`
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
```

`nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
| 28%   38C    P8    11W / 120W |    393MiB /  6075MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1110      G   /usr/lib/xorg/Xorg                           234MiB |
|    0      1708      G   cinnamon                                     103MiB |
|    0      1924      G   ...passed-by-fd --v8-snapshot-passed-by-fd    54MiB |
+-----------------------------------------------------------------------------+
```

```
----------Python Info----------
Version      : 3.5.2
Compiler     : GCC 5.4.0 20160609
Build        : ('default', 'Nov 23 2017 16:37:01')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 18.1
Directory    : /usr/local/lib/python3.5/dist-packages/pip
----------MXNet Info-----------
Version      : 1.3.0
Directory    : /usr/local/lib/python3.5/dist-packages/mxnet
Commit Hash   : b3be92f4a48bce62a5a8424271871c2f81c8f7f1
----------System Info----------
Platform     : Linux-4.4.0-137-generic-x86_64-with-Ubuntu-16.04-xenial
system       : Linux
node         : R2D17
release      : 4.4.0-137-generic
version      : #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 94
Model name:            Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Stepping:              3
CPU MHz:               3799.960
CPU max MHz:           3900,0000
CPU min MHz:           800,0000
BogoMIPS:              7007.87
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
```

**Comment by JackTemaki** [comment]
I actually solved the problem. I do not know exactly how it appeared, but after purging all cuda and nvidia stuff, reinstalling the 390 driver, installing cuda 9.1 from a runfile and not apt, it worked. Then after upgrading to 396.54 it still worked, and now also with cuda 9.2

It seems this is an Ubuntu 16.04 issue when installing cuda from apt and then updating to 396 and has nothing to do with mxnet...

**Comment by vrakesh** [comment]
@JackTemaki  Thanks for posting the issue and glad you were able to resolve it

**Comment by vrakesh** [comment]
@mxnet-label-bot [Installation, GPU]

**Comment by piyushghai** [comment]
@JackTemaki If this issue is resolved for you can you close the issue :) ?

**Comment by piyushghai** [comment]
@sandeep-krishnamurthy Requesting this issue to be closed since the author has resolved the issue :)
