### ISSUE TITLE
Quick installation finished but unable to run examples

### ISSUE THREAD

**Issue by mahmoodn** [apache/incubator-mxnet#14205]
The quick installation script for ubuntu seems to finished without problem.

```
$ ./install_mxnet_ubuntu_python.sh 
+ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                     
Hit:2 http://ppa.launchpad.net/ubuntuhandbook1/audacity/ubuntu bionic InRelease                                             
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]           
Fetched 177 kB in 1s (176 kB/s)                                                                 
Reading package lists... Done
+ sudo apt-get install -y apt-transport-https build-essential ca-certificates cmake curl git libatlas-base-dev libcurl4-openssl-dev libjemalloc-dev liblapack-dev libopenblas-dev libopencv-dev libzmq3-dev ninja-build python-dev python3-dev software-properties-common sudo unzip virtualenv wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
ca-certificates is already the newest version (20180409).
cmake is already the newest version (3.10.2-1ubuntu2).
liblapack-dev is already the newest version (3.7.1-4ubuntu1).
python-dev is already the newest version (2.7.15~rc1-1).
sudo is already the newest version (1.8.21p2-3ubuntu1).
unzip is already the newest version (6.0-21ubuntu1).
libatlas-base-dev is already the newest version (3.10.3-5).
libjemalloc-dev is already the newest version (3.6.0-11).
libopenblas-dev is already the newest version (0.2.20+ds-4).
ninja-build is already the newest version (1.8.2-1).
virtualenv is already the newest version (15.1.0+ds-1.1).
curl is already the newest version (7.58.0-2ubuntu3.6).
git is already the newest version (1:2.17.1-1ubuntu0.4).
libcurl4-openssl-dev is already the newest version (7.58.0-2ubuntu3.6).
wget is already the newest version (1.19.4-1ubuntu2.1).
libopencv-dev is already the newest version (3.2.0+dfsg-4ubuntu0.1).
libzmq3-dev is already the newest version (4.2.5-1ubuntu0.1).
python3-dev is already the newest version (3.6.7-1~18.04).
software-properties-common is already the newest version (0.96.24.32.7).
apt-transport-https is already the newest version (1.6.8).
0 upgraded, 0 newly installed, 0 to remove and 360 not upgraded.
+ wget -nv https://bootstrap.pypa.io/get-pip.py
2019-02-19 19:06:51 URL:https://bootstrap.pypa.io/get-pip.py [1702513/1702513] -> "get-pip.py.3" [1]
+ echo 'Installing for Python 3...'
Installing for Python 3...
+ sudo python3 get-pip.py
The directory '/home/mahmood/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mahmood/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d7/41/34dd96bd33958e52cb4da2f1bf0818e396514fd4f4725a79199564cd0c20/pip-19.0.2-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 911kB/s 
Installing collected packages: pip
  Found existing installation: pip 19.0.2
    Uninstalling pip-19.0.2:
      Successfully uninstalled pip-19.0.2
Successfully installed pip-19.0.2
+ pip3 install --user -r requirements.txt
Requirement already satisfied: cpplint==1.3.0 in /home/mahmood/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: h5py==2.8.0rc1 in /home/mahmood/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (2.8.0rc1)
Requirement already satisfied: nose in /home/mahmood/.local/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (1.3.7)
Requirement already satisfied: nose-timer in /home/mahmood/.local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (0.7.4)
Requirement already satisfied: numpy<=1.15.2,>=1.8.2 in /home/mahmood/.local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (1.15.2)
Requirement already satisfied: pylint==1.8.3 in /home/mahmood/.local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (1.8.3)
Requirement already satisfied: requests<2.19.0,>=2.18.4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.18.4)
Requirement already satisfied: scipy==1.0.1 in /home/mahmood/.local/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: six in /home/mahmood/.local/lib/python3.6/site-packages (from h5py==2.8.0rc1->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: mccabe in /home/mahmood/.local/lib/python3.6/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (0.6.1)
Requirement already satisfied: isort>=4.2.5 in /home/mahmood/.local/lib/python3.6/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (4.3.4)
Requirement already satisfied: astroid<2.0,>=1.6 in /home/mahmood/.local/lib/python3.6/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (1.6.5)
Requirement already satisfied: wrapt in /home/mahmood/.local/lib/python3.6/site-packages (from astroid<2.0,>=1.6->pylint==1.8.3->-r requirements.txt (line 6)) (1.11.1)
Requirement already satisfied: lazy-object-proxy in /home/mahmood/.local/lib/python3.6/site-packages (from astroid<2.0,>=1.6->pylint==1.8.3->-r requirements.txt (line 6)) (1.3.1)
+ echo 'Installing for Python 2...'
Installing for Python 2...
+ sudo python2 get-pip.py
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
The directory '/home/mahmood/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mahmood/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d7/41/34dd96bd33958e52cb4da2f1bf0818e396514fd4f4725a79199564cd0c20/pip-19.0.2-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 1.2MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.0.2
    Uninstalling pip-19.0.2:
      Successfully uninstalled pip-19.0.2
Successfully installed pip-19.0.2
+ pip2 install --user -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: cpplint==1.3.0 in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: h5py==2.8.0rc1 in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (2.8.0rc1)
Requirement already satisfied: nose in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.3.7)
Requirement already satisfied: nose-timer in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (0.7.4)
Requirement already satisfied: numpy<=1.15.2,>=1.8.2 in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (1.15.2)
Requirement already satisfied: pylint==1.8.3 in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (1.8.3)
Requirement already satisfied: requests<2.19.0,>=2.18.4 in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (2.18.4)
Requirement already satisfied: scipy==1.0.1 in /home/mahmood/.local/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: six in /home/mahmood/.local/lib/python2.7/site-packages (from h5py==2.8.0rc1->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: singledispatch; python_version < "3.4" in /home/mahmood/.local/lib/python2.7/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (3.4.0.3)
Requirement already satisfied: astroid<2.0,>=1.6 in /home/mahmood/.local/lib/python2.7/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (1.6.5)
Requirement already satisfied: configparser; python_version == "2.7" in /home/mahmood/.local/lib/python2.7/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (3.7.1)
Requirement already satisfied: backports.functools-lru-cache; python_version == "2.7" in /home/mahmood/.local/lib/python2.7/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (1.5)
Requirement already satisfied: mccabe in /home/mahmood/.local/lib/python2.7/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (0.6.1)
Requirement already satisfied: isort>=4.2.5 in /home/mahmood/.local/lib/python2.7/site-packages (from pylint==1.8.3->-r requirements.txt (line 6)) (4.3.4)
Requirement already satisfied: idna<2.7,>=2.5 in /home/mahmood/.local/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->-r requirements.txt (line 7)) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/mahmood/.local/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->-r requirements.txt (line 7)) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/mahmood/.local/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->-r requirements.txt (line 7)) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/mahmood/.local/lib/python2.7/site-packages (from requests<2.19.0,>=2.18.4->-r requirements.txt (line 7)) (3.0.4)
Requirement already satisfied: wrapt in /home/mahmood/.local/lib/python2.7/site-packages (from astroid<2.0,>=1.6->pylint==1.8.3->-r requirements.txt (line 6)) (1.11.1)
Requirement already satisfied: enum34>=1.1.3; python_version < "3.4" in /home/mahmood/.local/lib/python2.7/site-packages (from astroid<2.0,>=1.6->pylint==1.8.3->-r requirements.txt (line 6)) (1.1.6)
Requirement already satisfied: lazy-object-proxy in /home/mahmood/.local/lib/python2.7/site-packages (from astroid<2.0,>=1.6->pylint==1.8.3->-r requirements.txt (line 6)) (1.3.1)
Requirement already satisfied: futures in /home/mahmood/.local/lib/python2.7/site-packages (from isort>=4.2.5->pylint==1.8.3->-r requirements.txt (line 6)) (3.2.0)
+ cd ../../
+ echo 'Checking for GPUs...'
Checking for GPUs...
++ which nvidia-smi
++ wc -l
+ gpu_install=1
+ '[' 1 = 0 ']'
+ make_params='USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1'
+ echo 'nvidia-smi found! Installing with CUDA and cuDNN support with these build flags: USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1'
nvidia-smi found! Installing with CUDA and cuDNN support with these build flags: USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1
+ echo 'Building MXNet core. This can take few minutes...'
Building MXNet core. This can take few minutes...
++ nproc
+ make -j 16 USE_OPENCV=1 USE_BLAS=openblas USE_CUDA=1 USE_CUDA_PATH=/usr/local/cuda USE_CUDNN=1
Makefile:187: "USE_LAPACK disabled because libraries were not found"
INFO: nvcc was not found on your path
INFO: Using /usr/local/cuda/bin/nvcc as nvcc path
Running CUDA_ARCH: -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=[sm_75,compute_75] --fatbin-options -compress-all
mkdir -p /home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn/build/install
cd /home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core; make libdmlc.a USE_SSE=1 config=/home/mahmood/mx/incubator-mxnet/make/config.mk; cd /home/mahmood/mx/incubator-mxnet
cd /home/mahmood/mx/incubator-mxnet/3rdparty/tvm/nnvm; make lib/libnnvm.a DMLC_CORE_PATH=/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core; cd /home/mahmood/mx/incubator-mxnet
make[1]: Entering directory '/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core'
make[1]: Entering directory '/home/mahmood/mx/incubator-mxnet/3rdparty/tvm/nnvm'
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/core/pass.o src/core/pass.cc >build/src/core/pass.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/correct_layout.o src/pass/correct_layout.cc >build/src/pass/correct_layout.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/c_api/c_api_graph.o src/c_api/c_api_graph.cc >build/src/c_api/c_api_graph.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/core/node.o src/core/node.cc >build/src/core/node.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/gradient.o src/pass/gradient.cc >build/src/pass/gradient.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/plan_memory.o src/pass/plan_memory.cc >build/src/pass/plan_memory.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/print_graph_ir.o src/pass/print_graph_ir.cc >build/src/pass/print_graph_ir.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/c_api/c_api_symbolic.o src/c_api/c_api_symbolic.cc >build/src/c_api/c_api_symbolic.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/core/op.o src/core/op.cc >build/src/core/op.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/c_api/c_api_error.o src/c_api/c_api_error.cc >build/src/c_api/c_api_error.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/core/symbolic.o src/core/symbolic.cc >build/src/core/symbolic.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/core/graph.o src/core/graph.cc >build/src/core/graph.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/infer_shape_type.o src/pass/infer_shape_type.cc >build/src/pass/infer_shape_type.d
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/order_mutation.o src/pass/order_mutation.cc >build/src/pass/order_mutation.d
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o line_split.o src/io/line_split.cc
cd /home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn && rm -rf external && cd scripts && ./prepare_mkl.sh && cd .. && cp -a external/*/* /home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn/build/install/.
/bin/sh: 1: cd: can't cd to scripts
mkldnn.mk:38: recipe for target '/home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.0' failed
make: *** [/home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.0] Error 2
make: *** Waiting for unfinished jobs....
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/saveload_json.o src/pass/saveload_json.cc >build/src/pass/saveload_json.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/order_mutation.cc -o build/src/pass/order_mutation.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/gradient.cc -o build/src/pass/gradient.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/c_api/c_api_symbolic.cc -o build/src/c_api/c_api_symbolic.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/core/node.cc -o build/src/core/node.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/c_api/c_api_error.cc -o build/src/c_api/c_api_error.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/c_api/c_api_graph.cc -o build/src/c_api/c_api_graph.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/core/op.cc -o build/src/core/op.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/infer_shape_type.cc -o build/src/pass/infer_shape_type.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/core/graph.cc -o build/src/core/graph.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/core/symbolic.cc -o build/src/core/symbolic.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/print_graph_ir.cc -o build/src/pass/print_graph_ir.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/core/pass.cc -o build/src/core/pass.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/correct_layout.cc -o build/src/pass/correct_layout.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/plan_memory.cc -o build/src/pass/plan_memory.o
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/saveload_json.cc -o build/src/pass/saveload_json.o
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o indexed_recordio_split.o src/io/indexed_recordio_split.cc
g++ -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -MM -MT build/src/pass/place_device.o src/pass/place_device.cc >build/src/pass/place_device.d
g++ -c -std=c++11 -Wall -O2 -Iinclude -fPIC -I../include -I../3rdparty/dlpack/include -I../3rdparty/HalideIR/src -I../topi/include -I/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core/include  -c src/pass/place_device.cc -o build/src/pass/place_device.o
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o recordio_split.o src/io/recordio_split.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o input_split_base.o src/io/input_split_base.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o io.o src/io.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o filesys.o src/io/filesys.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o local_filesys.o src/io/local_filesys.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o data.o src/data.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o recordio.o src/recordio.cc
g++ -c -O3 -Wall -Wno-unknown-pragmas -Iinclude -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0  -msse2 -o config.o src/config.cc
ar crv lib/libnnvm.a build/src/c_api/c_api_symbolic.o build/src/c_api/c_api_graph.o build/src/c_api/c_api_error.o build/src/core/pass.o build/src/core/symbolic.o build/src/core/node.o build/src/core/op.o build/src/core/graph.o build/src/pass/gradient.o build/src/pass/infer_shape_type.o build/src/pass/correct_layout.o build/src/pass/order_mutation.o build/src/pass/plan_memory.o build/src/pass/print_graph_ir.o build/src/pass/saveload_json.o build/src/pass/place_device.o
a - build/src/c_api/c_api_symbolic.o
a - build/src/c_api/c_api_graph.o
a - build/src/c_api/c_api_error.o
a - build/src/core/pass.o
a - build/src/core/symbolic.o
a - build/src/core/node.o
a - build/src/core/op.o
a - build/src/core/graph.o
a - build/src/pass/gradient.o
a - build/src/pass/infer_shape_type.o
a - build/src/pass/correct_layout.o
a - build/src/pass/order_mutation.o
a - build/src/pass/plan_memory.o
a - build/src/pass/print_graph_ir.o
a - build/src/pass/saveload_json.o
a - build/src/pass/place_device.o
make[1]: Leaving directory '/home/mahmood/mx/incubator-mxnet/3rdparty/tvm/nnvm'
ar cr libdmlc.a line_split.o indexed_recordio_split.o recordio_split.o input_split_base.o io.o filesys.o local_filesys.o data.o recordio.o config.o
make[1]: Leaving directory '/home/mahmood/mx/incubator-mxnet/3rdparty/dmlc-core'
```
However, I am not able to run the example below

```
$ cd ../../example/restricted-boltzmann-machine/
$ python binary_rbm_gluon.py  --num-epoch 1 --num-hidden 10
Traceback (most recent call last):
  File "binary_rbm_gluon.py", line 21, in <module>
    import mxnet as mx
ImportError: No module named mxnet
```

What is missing here?

**Comment by frankfliu** [comment]
@mxnet-label-bot add [build, CI, Installation]

**Comment by frankfliu** [comment]
@mahmoodn 
It seems your build is failed in the middle:
```
cd /home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn && rm -rf external && cd scripts && ./prepare_mkl.sh && cd .. && cp -a external/*/* /home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn/build/install/.
/bin/sh: 1: cd: can't cd to scripts
mkldnn.mk:38: recipe for target '/home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.0' failed
make: *** [/home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn/build/install/lib/libmkldnn.so.0] Error 2
make: *** Waiting for unfinished jobs....
```

Can you take a look if you have "scripts" folder in "/home/mahmood/mx/incubator-mxnet/3rdparty/mkldnn"?

Please make sure update your submodule:
```
git submodule update --recursive
```

**Comment by frankfliu** [comment]
@mxnet-label-bot add [pending requester info]

**Comment by mahmoodn** [comment]
Thank you. I will surely come back. I won't have access to the machine for one day or so.

**Comment by mahmoodn** [comment]
@frankfliu 
Hi, I tried from scratch with the git recursive option
```
$ git clone --recursive https://github.com/apache/incubator-mxnet mxnet
$ cd mxnet/docs/install
$ ./install_mxnet_ubuntu_python.sh
```
output logs are pasted as below

https://pastebin.com/fkndDDpu
https://pastebin.com/C7VbiCFb
https://pastebin.com/9C04ehSr

Everything look fine. However, I am still getting "no module mxnet" error for python.
```
$ export LD_LIBRARY_PATH=~/mx/mxnet/lib:$LD_LIBRARY_PATH
$ cd ../../example/restricted-boltzmann-machine/
$ python binary_rbm_gluon.py  --num-epoch 1 --num-hidden 10
Traceback (most recent call last):
  File "binary_rbm_gluon.py", line 21, in <module>
    import mxnet as mx
ImportError: No module named mxnet
$ pip list | grep mxnet
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

**Comment by mahmoodn** [comment]
OK I fixed it by these commands
```
$ cd python/
$ pip install --user -e .
$ pip list
```
and mxnet was in the list.
