### ISSUE TITLE
R/mxnet/cuda 10.1 error with op.h Check failed

### ISSUE THREAD

**Issue by asheetal** [apache/incubator-mxnet#14334]
Centos 7
R version 3.5.2
Cuda 10.1 
mxnet checkout v0.5
gcc 7.3.1
config.mk is as follows
>USE_OPENCV = 1
>BLAS = open
>USE_BLAS = openblas
>USE_CUDA = 1
>USE_CUDA_PATH = /usr/local/cuda
>USE_CUDNN = 1
>USE_MKLDNN = 0
>USE_NCCL = 1
>USE_NCCL_PATH = /opt/nccl/build

When I run the command
> model_keras <- keras_model_sequential() %>% multi_gpu_model()

This is the error I get
Error: [16:14:42] /opt/mxnet/3rdparty/tvm/nnvm/include/nnvm/op.h:461: Check failed: p.second != plevel Attribute FListInputNames of operator CuDNNBatchNorm is already registered with same plevel=10

Stack trace returned 10 entries:
[bt] (0) /usr/lib64/R/library/mxnet/libs/libmxnet.so(dmlc::StackTrace()+0x40) [0x7febe99936d0]
[bt] (1) /usr/lib64/R/library/mxnet/libs/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x2b) [0x7febe9993edb]
[bt] (2) /usr/lib64/R/library/mxnet/libs/libmxnet.so(nnvm::Op::set_attr<std::function<std::vector<std::string, std::allocator<std::string> > (nnvm::NodeAttrs const&)> >(std::string const&, std::function<std::vector<std::string, std::allocator<std::string> > (nnvm::NodeAttrs const&)> const&, int)::{lambda(dmlc::any*)#1}::operator()(dmlc::any*) const+0x54e) [0x7febe99a38be]
[bt] (3) /usr/lib64/R/library/mxnet/libs/libmxnet.so(nnvm::Op::UpdateAttrMap(std::string const&, std::function<void (dmlc::any*)>)+0xb7) [0x7febee7c7d67]
[bt] (4) /usr/lib64/R/lib

Anyone have any idea?

**Comment by asheetal** [comment]
Ah I found the problem. I was doing both keras mxnet backend as well as library(mxnet). I removed library(mxnet) this error went away
