### ISSUE TITLE
Install mxnet using pip

### ISSUE THREAD

**Issue by cuongngm** [apache/incubator-mxnet#20279]
## Description
I try to install mxnet using pip:
```
pip install mxnet-cu112
```
in some server using cuda 11.1 11.2 11.3 and google colab (cuda 11.2) but all the error when importing mxnet.

### Error Message
```
OSError: libnvrtc.so.11.2: cannot open shared object file: No such file or directory (in server with cuda 11.1)
OSError: libcusolver.so.11: cannot open shared object file: No such file or directory (in google colab - cuda 11.2)
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory (in server with cuda 11.2)
```

**Comment by leezu** [comment]
Please install the cudnn, cusolver and nvrtc libraries that are part of the NVIDIA CUDA libraries.

**Comment by cuongngm** [comment]
in gg colab, i installed mxnet-cu110 and this problem fixed. Same for my server, I solved it by installing mxnet-cu100.
