### ISSUE TITLE
OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xhniu** [apache/incubator-mxnet#3829]
I upgrade my nvidia drivers and cuda version;

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

When i finished all of it; i recompile the caffe and mxnet; the caffe work well,but the mxnet always remind me "OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory", don't how to modify my configuration. Thank you;

**Comment by piiswrong** [comment]
export LD_LIBRARY_PATH=/path/to/cuda/lib

**Comment by xhniu** [comment]
@piiswrong Thank you for your comments,my LD_LIBRARY_PATH is 
echo $LD_LIBRARY_PATH
/usr/local/cuda-8.0/lib64/stubs:/usr/local/cuda-8.0/lib64;
my cuda version is 8.0,i'm confused about why the mxnet always remind me "cannot open shared object libcudart.so.7.5"?

**Comment by piiswrong** [comment]
Edit config.mk to make sure usecudapath point to cuda8.0 then rebuild

**Comment by xhniu** [comment]
# add the path to CUDA library to link and compile flag                       
# if you have already add them to environment variable, leave it as NONE
USE_CUDA_PATH = /usr/local/cuda-8.0
My config.mk file /usr/local/cuda-8.0,i checked it again. There was no error when i rebuild the whole project. I'm not sure if there was any other configure file i should modify. Thank you. @piiswrong

**Comment by IvyGongoogle** [comment]
@xhniu Have you solve your problem? I have a same problem. I edit config.mk to make sure usecudapath point to cuda8.0 then rebuild. But when I import mxnet in python, it still show error:

```
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/congleng/work/deeplearning-tools/mxnet-cuda8/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/congleng/work/deeplearning-tools/mxnet-cuda8/python/mxnet/base.py", line 46, in <module>
    _LIB = _load_lib()
  File "/home/congleng/work/deeplearning-tools/mxnet-cuda8/python/mxnet/base.py", line 38, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/congleng/local/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory

```
why it always remind "cannot open shared object libcudart.so.7.5"?
@xhniu @piiswrong Can you give me some advices?
thank you in advance!

**Comment by piiswrong** [comment]
try pip install mxnet-cu80

**Comment by miraclewkf** [comment]
@IvyGongoogle Have you solved your problem?

**Comment by thakkarswadhin** [comment]
I was able to solve this issue by:
pip install mxnet-cu80

But the change I did - completely removed the mxnet git repo which I had downloaded. Seemed like that installation was over-riding the pip installation (NOTE that I was getting the same error as long as both were installed)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.

**Comment by rxqy** [comment]
@Alexander-flyer Hi, I have also encountered a similar problem here.
I'm using cuda-9.0, but mxnet keeps asking me to find libcudart.so.8.0.
Thought might be a problem with my opencv, can you tell me how you solved the problem?

**Comment by rohun-tripathi** [comment]
conda install -c anaconda cudatoolkit==9.2 (I faced it with 9.2) solves it for me in an anaconda environment.
I am still trying to determine the reason.
