### ISSUE TITLE
mx.contrib.sym.ctc_loss slow down extremely on gpu with large alphabet_size,but faster on cpu

### ISSUE THREAD

**Issue by dianyancao** [apache/incubator-mxnet#7154]
When I train large alphabet with size say > 3000 on gpu the mx.contrib.sym.ctc_loss training speed is very slow 0.2 samples per second, but on cpu the speed is faster 16 samples per second.
How to get work with mx.contrib.sym.ctc_loss when the alphabet_size is large?

**Comment by dianyancao** [comment]
/dot_engine-inl.h:616: Check failed: err == CUBLAS_STATUS_SUCCESS (14 vs. 0) Cublas: Dot fail

**Comment by dianyancao** [comment]
I bind feature module to gpu and bind loss module to cpu,now it works.
The problem maybe caused by the gpu memory managment.

**Comment by goodtogood** [comment]
same problem, would you like to share your code ?
thx!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
