### ISSUE TITLE
OSError: libcudart.so.8.0: cannot open shared object 

### ISSUE THREAD

**Issue by rnunziata** [apache/incubator-mxnet#7608]
Paths are correct...the library(libcudart.so.8.0) is present....it compiles without error. Environment vars are set correctly for cuda-8 with cudnn-6. running on ubuntu 16.04.  Can not figure out what is happening to cause this error. Is this a cuda issue, and nivida issue, tensorflow issue...any help please.

```
Traceback (most recent call last):
  File "./fcis/demo.py", line 27, in <module>
    import mxnet as mx
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 46, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 38, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.8.0: cannot open shared object file: No such file or directory

```

**Comment by xzqjack** [comment]
I have similar issue when i use tensorflow, even when i set the cuda/lib64 path in ~/.bashrc. The below code works for me. You can have a try. Path is the cuda lib64 that may be different from yours.
```
sudo sh -c "echo '/usr/local/cuda/lib64\n/usr/local/cuda/lib' >> /etc/ld.so.conf.d/nvidia.conf"
sudo ldconfig
```

**Comment by rnunziata** [comment]
Thanks this seems to have worked....thanks so much..:-)
