### ISSUE TITLE
out of memory error on windows

### ISSUE THREAD

**Issue by caiqi** [apache/incubator-mxnet#8041]
## Environment info
Operating System:

Windows Server 2016

MXNet version:
0.11.0

Or if installed from source:
Install with pip install mxnet-cu80

Python version and distribution:
2.7

run python train_mnist.py in examples folder would cause out of memory error, which is weird since the memory is sufficient enough.

> [17:45:39] G:\deeplearn\mxnet\dmlc-core\include\dmlc/logging.h:308: [17:45:39] g:\deeplearn\mxnet\src\storage\./pinned_memory_storage.h:54: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
> [17:45:39] G:\deeplearn\mxnet\dmlc-core\include\dmlc/logging.h:308: [17:45:39] g:\deeplearn\mxnet\src\engine\./threaded_engine.h:347: [17:45:39] g:\deeplearn\mxnet\src\storage\./pinned_memory_storage.h:54: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
> An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
>

**Comment by Bumblebee1964** [comment]
Is it possible to install python package on Windows with pip???? Any documentation about this, I couldn't find it. Just type pip install mxnet-cu80 is sufficient?

**Comment by caiqi** [comment]
According to this issue, it can be installed with pip. https://github.com/apache/incubator-mxnet/issues/7362 . However, it always fails with out of memory on multi GPUs training in my experiments.

**Comment by zhreshold** [comment]
Can you create a large matrix on gpu to test?
For example
```
import mxnet as mx
a = mx.nd.ones(shape=(256, 1024, 2000), ctx=mx.gpu(0))
```
will create a 2000M matrix on gpu

**Comment by caiqi** [comment]
It works fine creating a large matrix on GPU. However when I run train_mnist.py it still fails and the python stop working. The GPU is M40. I tried run train_mnist.py on K40, it works fine.

**Comment by zhreshold** [comment]
@yajiedesign

**Comment by yajiedesign** [comment]
how many you system physics memory?this is alloc pinned memory.it must enough physics memory.

**Comment by caiqi** [comment]
The free physical memory is enough. I just found that it's due to GPU 0 is broken. Even I set to use other GPUS it still fails. If I set CUDA_VISIBLE_DEVICES to mask GPU 0, the code can work without errors.  Thank you for your reply.

**Comment by Bumblebee1964** [comment]
I got mxnet with python installed on Windows 10 with pip using Anaconda 2. Seems to work with VS2017, although Anaconda2 has to be installed with the VS2017 installer. Thank you for the tips! 

Would be good if using pip install for Windows is reference on the installation webpage of mxnet.io . Really saves tons of work.

**Comment by Bumblebee1964** [comment]
Unfortunately the mxnet pyhton on windows through 'pip install -U --pre mxnet' does not run on GPU:
 
C:\projects\mxnet-distro-win\mxnet-build\dmlc-core\include\dmlc/logging.h:308: [16:09:26] C:\projects\mxnet-distro-win\mxnet-build\src\storage\storage.cc:113: Compile with USE_CUDA=1 to enable GPU usage

Is it possible to pip install a version with gpu support?

**Comment by caiqi** [comment]
I install mxnet by **pip install mxnet-cu80** so that I can use GPU.

**Comment by Bumblebee1964** [comment]
Thanks, I should have read the thread #7362 better. But yeah, it works now!!! many thanx.
