### ISSUE TITLE
(err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by 2016xjtuzyt** [apache/incubator-mxnet#8443]
HI thanks for your help!
When I am trying to build with CUDNN, I've got the following error when running the mnist example

[10:55:50] ~/mxnet/dmlc-core/include/dmlc/logging.h:235: 
[10:55:50] ~/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_NOT_INITIALIZED
[10:55:50] ~/mxnet/dmlc-core/include/dmlc/logging.h:235: 
[10:55:50]~/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_NOT_INITIALIZED
terminate called after throwing an instance of 'dmlc::Error'
  what():  
[10:55:50] ~/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_NOT_INITIALIZED
terminate called recursively

However, it works with CPU.
I have succeeded before! but after awhile when i make again, the above problem occur！

CentOS 6.5
CUDA 8.0
CUDNN is 5.0
Tesla M40

**Comment by anirudh2290** [comment]
What is your hardware setup? cuDNN supports devices with compute capabilites of greater than or equal to 3.0 only.

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by b0noI** [comment]
Suggested tags: "Bug"

**Comment by 2016xjtuzyt** [comment]
the problem has been solved by update cuda driver!
